//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DokumentMagazynowy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dokument_magazynowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dokument_magazynowy()
        {
            this.pozycja_dokumentu_magazynowego = new HashSet<pozycja_dokumentu_magazynowego>();
        }
    
        public int id_dokumentu_magazynowego { get; set; }
        public System.DateTime data { get; set; }
        public int numer_klienta { get; set; }
        public string nazwa { get; set; }
        public Nullable<decimal> cena_netto { get; set; }
        public Nullable<decimal> cena_brutto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pozycja_dokumentu_magazynowego> pozycja_dokumentu_magazynowego { get; set; }
    }
}
